version: "3"
services:
  mongodb:
    restart: always
    container_name: app-db
    image: mongo
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - express-mongo

  client:
    container_name: app-client
    build: ./client
    expose:
        - 4000   
    ports:
        - 4000:4000
    volumes:
        - ./client/src:/srv/app/client/src
        - ./client/public:/srv/app/client/public
    stdin_open: true
    command: npm run start
    networks:
      - react-express
    depends_on:
      - server

  server:
    container_name: app-server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    expose:
        - 3000
    ports:
        - 3000:3000
    volumes:
        - ./server/src:/srv/app/admin-server/src
    links:
        - mongodb
    depends_on:
        - mongodb    
    networks:
        - express-mongo
        - react-express
    command: dev

networks:
  react-express:
  express-mongo:
